BATCH_SIZE = 128
CLASS_COUNT = 7

IMAGE_WIDTH = 48
IMAGE_HEIGHT = 48
IMAGE_SIZE = IMAGE_WIDTH * IMAGE_HEIGHT

# keras models
MODEL_ROOT = 'models/keras'
REGULARIZED_MODEL_PATH = MODEL_ROOT + '/cnn_regularized.model.md5'
REGULARIZED_WEIGHTS_PATH = MODEL_ROOT + '/cnn_regularized.weights.md5'

